### ISSUE TITLE
scrap checklist

### ISSUE THREAD

**Issue by fazalfarruq** [fazalfarruq/scrap#1]
## Class Checklist

- [x] Create an issue
- [x] Create a branch
- [ ] Make commits
- [ ] Open a pull request
- [x] Collaborate
- [ ] Merge pull requests
- [ ] Have a good day ❇️
